### ISSUE TITLE
비로그인시 classinsert창 요청 문제

### ISSUE THREAD

**Issue by Jaehyunleejava** [yjkwon07/TS_PJ#10]
로그인시 classinsert창으로 연결되는데

*그냥 classinsert창을 요청하면 오류가 남(추후에 해결할 예정)

**Comment by yjkwon07** [comment]
interceptor에 문제 발생 가능성이 높아 보이네여

**Comment by yjkwon07** [comment]
#21  단순 코드 문제였으며 
logoutpost 구현으로 session 만료일 수정
