### ISSUE TITLE
controller에서 json만들어서 view로 넘기는 문제

### ISSUE THREAD

**Issue by Jaehyunleejava** [yjkwon07/TS_PJ#17]
![리얼2](https://user-images.githubusercontent.com/45728768/64921412-03631180-d7fe-11e9-96a4-c9d4693cb7ab.PNG)
![1](https://user-images.githubusercontent.com/45728768/64921413-052cd500-d7fe-11e9-9d6b-9cb2c2ceecd6.PNG)

첫번째 그림처럼, controller에서 jsonOject를 이용해서 ModelAndView에 model를 넘겨주었는데 아래 그림 view에서 인식을 못한다.

**Comment by Jaehyunleejava** [comment]
![image](https://user-images.githubusercontent.com/45728768/64921459-4de48e00-d7fe-11e9-9ce2-36edd0923c8b.png)
그래서 JsonObject를 사용할 필요없이 자바에서 만든 map객체를 Gson 라이브러리를 이용해서 model에 추가해서 문제를 해결했다.

**Comment by Jaehyunleejava** [comment]
GSON는 json 형태를 자바 객체로 변환하는데 사용할 수 있도록 구글에서 제공한 자바 라이브러리 입니다.
Jackson 또한 GSON과 마찬가지로 json 형태를 자바 객체로, 자바 객체를 json 형태로 변환해주는 자바 라이브러리 입니다.

적은 데이터에는 Gson이 우수, 많은 데이터에서 jackson이 우수합니다.

https://tomining.tistory.com/27

**Comment by yjkwon07** [comment]
https://doublesprogramming.tistory.com/204
