### ISSUE TITLE
classinsert view issue

### ISSUE THREAD

**Issue by Jaehyunleejava** [yjkwon07/TS_PJ#19]
![image](https://user-images.githubusercontent.com/45728768/64949958-4c29d180-d8b5-11e9-9228-405f6817299d.png)
DB를 보면 이 부분이 한개 컬럼으로 되어있는데, 여기서는 두개 컬럼이 필요하게 되어있습니다.
그래서 DB컬럼을 추가 할 것인지, 한개 값으로 바꿀것인지 결정해야할 것 같습니다.

**Comment by yjkwon07** [comment]
1) 컨트롤 부분에서 강의 가능한 날짜 부분의 start값과 end값을 컬럼 값에 맞게 포맷팅 하는 방법
2) 각 요일에 맞게 hidden input 태그를 만든 후 js에서 이벤트 리스너를 사용하여 박스의 값이 수정할 때마다 input (hidden) 태그에 DB컬럼에 맞게 값을 포맷팅 하는 방법
* 개인적으로 vo나 변수를 추가하는것 보다 후자의 방법으로 해결하는것이 더 괜찮을거 같아요.

**Comment by Jaehyunleejava** [comment]
https://its-easy.tistory.com/12

**Comment by yjkwon07** [comment]
#17 [code](https://github.com/yjkwon07/TS_PJ/pull/27/commits/5bed364d6049674c93b449e381d5b9725fcd637b#diff-4879a13b9816bf790bcb0898672c3cda)

js에서 시작 시간과 끝나는 시간이 표시된곳을 querySelector로 태그를 찾아서 
startTime ~ endTime 으로 가공했습니다. 
![code](https://user-images.githubusercontent.com/31876632/66027899-db321d00-e536-11e9-92d5-eb153934e333.png)
