### ISSUE TITLE
강의 업로드페이지에서 user_id, class_teacher_id 처리

### ISSUE THREAD

**Issue by Jaehyunleejava** [yjkwon07/TS_PJ#2]
form태그를 이용해서 controller로 보낼 때,  *처리 어떻게 처리할까요?

```
<input type="hidden" name="user_id" value="*********">
<input type="hidden" name="class_teacher_name" value="*********">

```
* 값을 어디서 받아올수 있을까요?
로그인 된 인터셉션을 이용하면 될거같은데 잘 안떠오르네요

**Comment by yjkwon07** [comment]
강좌 insert부분인가요? 
강좌 insert부분이면 로그인이 되었는지 확인을 하고  튜터인지 auth체크 후에 
user_id 를 기입 하고 class_teacher_name은 mapper명세 부분에 select user부분 참고해서 user_name을 불러오면 될거 같아요.
2) 아니면 세션에 저장할 때 user_id와 user_name을 저장하고 hidden에 넣어주는것도 있겠네요 
처음부터 로그인이 되었을 시점에서 mapper명세에서 select user 부분을 참고해서 id와 name을 세션에 저장하고 사용하면 더 좋을거 같아요

**Comment by Jaehyunleejava** [comment]
2번 방법으로 해결했습니다
